### ISSUE TITLE
yarn第一步就报错

### ISSUE THREAD

**Issue by BoFan-tunning** [fxjhello/langchain_chatglm_nest#1]
![image](https://user-images.githubusercontent.com/129488076/235040039-e5d7684d-2298-4003-b770-398b436d0da5.png)

**Comment by fxjhello** [comment]
langchain需要python3.8以后和c++环境

**Comment by oubeishi** [comment]
![Snipaste_2023-04-28_10-51-31](https://user-images.githubusercontent.com/114290647/235043119-db3cb805-1d55-4680-9797-b57465aaae3a.png)
![Snipaste_2023-04-28_10-53-10](https://user-images.githubusercontent.com/114290647/235043218-d272fbe5-75d7-4d20-b340-07568a90dbd1.png)
c++在visual studio里下载，python官网下

**Comment by BoFan-tunning** [comment]
![image](https://user-images.githubusercontent.com/129488076/235071234-f97750c7-a435-451b-99a6-bbfa690643e3.png)

**Comment by BoFan-tunning** [comment]
python 是3.10

**Comment by oubeishi** [comment]
试一下在命令行输入npm install -g node-gyp

**Comment by oubeishi** [comment]
![Snipaste_2023-05-05_14-37-04](https://user-images.githubusercontent.com/114290647/236391525-3ed23371-7beb-416a-a1b2-a2ebfb0da3e3.png)
补充一点，是vectorStore会用到c++，故需要安装visual studio。
https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/hnswlib

**Comment by fxjhello** [comment]
已解决
